export { downloadFile } from './downloadFile'
export { gbkToUtf8 } from './gbkToUtf8'
export { getUUID } from './getUUID'
export { getUrlParam } from './getUrlParam'
export { scrollTo } from './scrollTo'
export { phoneEncrypt } from './phoneEncrypt'
